name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:alpine
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

      #- name: Test
      #run: go test -v .

    - name: Docker login github
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build container
      run: |
        docker tag workflow-test ${{ secrets.DOCKER_USER }}/workflow-test:${{ github.sha }}
        docker tag workflow-test ${{ secrets.DOCKER_USER }}/workflow-test:latest

    - name: push package
      run: |
        docker push ${{ secrets.DOCKER_USER }}/workflow-test:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/workflow-test:latest
    
