name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    #container:
    #  image: golang:alpine
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

      #- name: Test
      #run: go test -v .

    - name: Login to GitHub Package Registry
      run: docker login docker.pkg.github.com -u ${{ github.repository }} -p ${{ secrets.GITHUB_TOKEN }}
      #uses: docker/login-action@v1
      #with:
      #  registry: docker.pkg.github.com
      #  username: ${{ github.repository_owner }}
      #  password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build container
      run: docker build -t workflow-test .
      
    - name: Tag container
      run: docker tag workflow-test docker.pkg.github.com/juliovr/workflow-test/workflow-test:latest
          #docker tag workflow-test docker.pkg.github.com/juliovr/workflow-test/workflow-test:${{ github.sha }}
          #docker tag workflow-test docker.pkg.github.com/juliovr/workflow-test/workflow-test:latest

    - name: push package
      run: docker push docker.pkg.github.com/juliovr/workflow-test/workflow-test:latest
          #docker push docker.pkg.github.com/juliovr/workflow-test/workflow-test:${{ github.sha }}
          #docker push docker.pkg.github.com/juliovr/workflow-test/workflow-test:latest
